version: '3.8'

services:
  database:
    image: mysql:latest
    command: 
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${PORT}:3306'
    volumes:
      - database_storage:/var/lib/mysql
volumes:
  database_storage: